version: '3.5'

services:
  db:
    image: mariadb:10.5.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
      - "./mysql-init-files:/docker-entrypoint-initdb.d"
    environment:
      - "TZ"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always
    
  app:
    image: kodcloud/kodbox:v1.12-fpm-alpine
    volumes:
      - "./data:/var/www/html"
    environment:
      - "MYSQL_SERVER"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
      - "REDIS_HOST"
    restart: always

  web:
    image: nginx:1.19.2
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data:/var/www/html:ro"
    depends_on:
      - app
    restart: always
    
  redis:
    image: redis:alpine3.12
    restart: always
